### ISSUE TITLE
repo discussions and descriptions

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_x_multi_bloc#1]
Under the settings for the repo, add discussions.

![image](https://user-images.githubusercontent.com/5799860/174325023-995e419e-fe21-408a-b077-05845dfb1182.png)

![image](https://user-images.githubusercontent.com/5799860/174324184-9af5c45e-e657-4776-87af-ea982bfdd00a.png)

![image](https://user-images.githubusercontent.com/5799860/174324689-76116b23-7386-4ff4-b08e-be3aa576d693.png)

---

## description

Under About, add description of project

![image](https://user-images.githubusercontent.com/5799860/174325495-4e00d1cb-cab4-4bf5-a127-a7331fa9bb5a.png)

**Comment by jcasman** [comment]
Concept for 2-screen bloc app. 

First screen is called Use Camera

- There is one big round button, a shutter button. If not recording video, it does startCapture. If recording video, it does stopCapture.

Second screen is called Video Settings

- There are buttons for 8K 2fps, 8k 10 fps, 4k 30fps.
- There are buttons for bitrate: Fine, Normal, or Economy
- There is a button for video stitching: ON/OFF

Note: If Caitlyn is only developing one button for the second screen, just do 8K 2fps.

**Comment by codetricity** [comment]
I was suggesting to start a discussion at the link below instead of opening an issue:

https://github.com/codetricity/oppkey_theta_x_app_status/discussions

> Concept for 2-screen bloc app.
> 
> First screen is called Use Camera
> 
> * There is one big round button, a shutter button. If not recording video, it does startCapture. If recording video, it does stopCapture.

likely do not implement camera mode check as there is no working example of us doing this.  We'd need to check if the app is connected to the camera or not.  We'd be able to do this on the emulator, but I'm not sure if it's feasible on the physical device at this stage.

Would be easier to implement something like:

```mermaid
graph TD;
    modeButton-->takePictureButton;
    modeButton-->startCaptureButton;
```
 
or 

```mermaid
graph TD;
    takePictureButton;
    startCaptureButton
```

The easiest thing would be this:


```mermaid
graph TD;
    takePictureButton;
    startCaptureButton
```


> 
> Second screen is called Video Settings
> 
> * There are buttons for 8K 2fps, 8k 10 fps, 4k 30fps.
> * There are buttons for bitrate: Fine, Normal, or Economy
> * There is a button for video stitching: ON/OFF
> 
> Note: If Caitlyn is only developing one button for the second screen, just do 8K 2fps
