### ISSUE TITLE
Concept for 2-screen bloc app.

### ISSUE THREAD

**Issue by caitlynbakery** [caitlynbakery/theta_x_multi_bloc#2]
Concept for 2-screen bloc app from @jcasman 

First screen is called Use Camera

- There is one big round button, a shutter button. If not recording video, it does startCapture. If recording video, it does stopCapture.

Second screen is called Video Settings

- There are buttons for 8K 2fps, 8k 10 fps, 4k 30fps.
- There are buttons for bitrate: Fine, Normal, or Economy
- There is a button for video stitching: ON/OFF

Note: If Caitlyn is only developing one button for the second screen, just do 8K 2fps.

_Originally posted by @jcasman in https://github.com/caitlynbakery/theta_x_multi_bloc/issues/1#issuecomment-1159200191_

---

comment from @codetricity 

I was suggesting to start a discussion at the link below instead of opening an issue:

https://github.com/codetricity/oppkey_theta_x_app_status/discussions

> Concept for 2-screen bloc app.
> 
> First screen is called Use Camera
> 
> * There is one big round button, a shutter button. If not recording video, it does startCapture. If recording video, it does stopCapture.

likely do not implement camera mode check as there is no working example of us doing this.  We'd need to check if the app is connected to the camera or not.  We'd be able to do this on the emulator, but I'm not sure if it's feasible on the physical device at this stage.

Would be easier to implement something like:

```mermaid
graph TD;
    modeButton-->takePictureButton;
    modeButton-->startCaptureButton;
```
 
or 

```mermaid
graph TD;
    takePictureButton;
    startCaptureButton
```

The easiest thing would be this:

```mermaid
graph TD;
    takePictureButton;
    startCaptureButton
```

> 
> Second screen is called Video Settings
> 
> * There are buttons for 8K 2fps, 8k 10 fps, 4k 30fps.
> * There are buttons for bitrate: Fine, Normal, or Economy
> * There is a button for video stitching: ON/OFF
> 
> Note: If Caitlyn is only developing one button for the second screen, just do 8K 2fps

**Comment by jcasman** [comment]
OK, @caitlynbakery I see the direction of the app that you're working on. The startCapture button starts video recording. With this version, there is no way to stop the video recording through the app, correct? (Perfectly fine, just confirming.)

**Comment by codetricity** [comment]
> OK, @caitlynbakery I see the direction of the app that you're working on. The startCapture button starts video recording. With this version, there is no way to stop the video recording through the app, correct? (Perfectly fine, just confirming.)

I believe that is the intent.  As the primary objective is to use more than one BLoC, I believe we should reduce the feature set for this app to focus on the use of multiple blocs.

Here is the [official documentation on MultiBlocProvider](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/MultiBlocProvider-class.html) 


```dart
MultiBlocProvider(
  providers: [
    BlocProvider<BlocA>(
      create: (BuildContext context) => BlocA(),
    ),
    BlocProvider<BlocB>(
      create: (BuildContext context) => BlocB(),
    ),
    BlocProvider<BlocC>(
      create: (BuildContext context) => BlocC(),
    ),
  ],
  child: ChildA(),
)
```

If @caitlynbakery  wraps the `MultiBlocProvider` around the top-level `MaterialApp` with two blocs, it will look like this:

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<CameraUseBloc>(
          create: (context) => CameraUseBloc(),
        ),
        BlocProvider(
          create: (context) => VideoSettingsBloc(),
        )
      ],
      child: const MaterialApp(
        home: Scaffold(body: CameraUseScreen()),
      ),
    );
  }
}
```

Points

* this app does not have bloc-to-bloc communication.  An example of bloc-to-bloc communication would be to pass the URL of a thumbnail into the event to display a full-screen image.  I think it's good to keep the app simple for this version.
* To get from the 2nd screen back to the first screen, she can use `appBar: AppBar()` to get the default back button to pop the current screen from the navigation stack.

## First Screen 

```mermaid
graph TD;
    takePictureButton;
    startCaptureButton
    videoSettingsButton
```

## Second Screen

```mermaid
graph TD;
    Back_to_first_screen
    8K_2fps;
```

## Navigation Route

```mermaid
flowchart TD;
    SCREEN_firstScreen --> BUTTON_videoSettingsButton --> SCREEN_videoSettingScreen --> BUTTON_8K_2fps
```

**Comment by jcasman** [comment]
OK, I agree a gear icon does not suggest going back to the other screen. An arrow key in the top left corner is good.

**Comment by codetricity** [comment]
We can likely close this issue and discuss the next feature improvement set in topic #4 or the GoogleDoc that Caitlyn wrote.
