### ISSUE TITLE
_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_x_multi_bloc#5]
## Problem

The output of `response.body` is not a String. 

```text
ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
```

## Solution

use `response.bodyString` instead of `response.body`

```dart
      emit(CameraUseState(responseMessage: response.bodyString));
```

## Example

![image](https://user-images.githubusercontent.com/5799860/175181715-416f6819-3596-4b49-a4af-d1521ab243eb.png)

**Comment by caitlynbakery** [comment]
Fixed the issue ed346ecef8710901ead5a6a0d439bcaed8225301
