### ISSUE TITLE
Conform to linter rules

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_x_multi_bloc#6]
1. inspect linter rules in VS Code
2. fix problems or change rules to ignore a specific rule

![image](https://user-images.githubusercontent.com/5799860/175181987-327083d9-9917-4365-921f-00aee3798f5f.png)

## ignore rules in `analysis_options.yaml`

in rules:, uncomment `avoid_print: false`

![image](https://user-images.githubusercontent.com/5799860/175182203-cc17b7c3-a0d8-4fac-a003-00ed259e3f37.png)

![image](https://user-images.githubusercontent.com/5799860/175182351-80a62355-2f96-4557-9e63-f972d3a813be.png)

**Comment by caitlynbakery** [comment]
Fixed the linter rules and committed the changes. db2fb186c89c4db4efd2101fac58ec40c9d72bd1
